name: AdonisJs Workflow

on: push

jobs:
  testing:
    name: AdonisJs testing
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install mongo
        uses: ./.github/actions/mongodb
      - name: Install adonis
        uses: ./.github/actions/config-adonisjs
      - name: Adonis testing
        run: adonis test
        env:
          CI: true
