name: AdonisJs Workflow

on: push

jobs:
  testing:
    name: AdonisJs testing
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: mongodb
        uses: ./.github/actions/mongodb
      - name: Adonis
        uses: ./.github/actions/config-adonisjs
      - name: Init lint
        run: yarn lint
      - name: Init testing
        run: adonis test
      env:
        CI: true
